### ISSUE TITLE
Support for internalization misses

### ISSUE THREAD

**Issue by willypuzzle** [devstark-com/vue-google-charts#1]
There is no way to force the plugin to use the locale I want. In order to force the locale the plugin should call (for example): 

loader.load('current', { packages, 'language': 'it' })

But there is no way at the moment to do this. I suggest to add a prop in order to force the locale such as in google chart way.

**Comment by nobilix** [comment]
good point, will add this option soon

**Comment by nobilix** [comment]
Done! now you can do that:
```javascript
  <GChart
    :settings="{ packages: ['corechart', 'table', 'map'], language: 'it' }"
    type="Map"
    :data="chartData"
    :options="chartOptions"
  />
```
`packages` prop is removed, use `settings` prop instead.

#2
