### ISSUE TITLE
Chart does not resize

### ISSUE THREAD

**Issue by focussing** [devstark-com/vue-google-charts#15]
I am using the chart in Bootstrap row of 50% width.
The chart does not rescale, it seem it has a fixed height (200px) and width (540px).
Setting via chartOptions is only working for other fixed height and width.

**Comment by nobilix** [comment]
Hey guys! Please use the latest version in order to make GChart responsive.
The example above uses `0.1.0`, and if you upgrade it to `0.3.1` it becomes responsive without any change in the props.

@alexxlagutin please upgrade the examples' version.
