### ISSUE TITLE
Custom dataTable as data prop param

### ISSUE THREAD

**Issue by piotr-pilis** [devstark-com/vue-google-charts#16]
Hi,

In my use case I need to define custom dataTable (2 columns and one tooltip column). Is there a way to make dataTable before chart loads?

**Comment by nobilix** [comment]
Hi,

> Is there a way to make dataTable before chart loads?

If I get your case right you can just apply a simple `v-if` directive to the `<GChart>` component and pass some computed which is aware if the dataTable is made

**Comment by Thyvo** [comment]
Hi,

Would it be possible to show us an example of this?

**Comment by boka18** [comment]
Hello @nobilix ! 
I'm using the GeoChart type. I'd like my tooltip to be formatted as: `$123,22`. I did a lot of research and I wasn't able to do that. Is there a way to do it?
