### ISSUE TITLE
Is it possible to hide/show series?

### ISSUE THREAD

**Issue by Tropicalista** [devstark-com/vue-google-charts#17]
I'm trying to hide/show series by clicking on legend.

Is this possible? any example?

https://codesandbox.io/s/mj7nokl0ny

**Comment by alexxlagutin** [comment]
Hi! @Tropicalista. Check this https://github.com/devstark-com/vue-google-charts#add-event-listeners and this example: Chart event handling https://codesandbox.io/embed/xlloookqqo?module=%2Fsrc%2FApp.vue

**Comment by Tropicalista** [comment]
Solved, thanks!
