### ISSUE TITLE
Breaking changes on a MINOR version bump.

### ISSUE THREAD

**Issue by MrDrummer** [devstark-com/vue-google-charts#179]
We use this package on a Vue 2 based website.

We use Renovate to automatically bump minor and patch versions.

The 0.4.0 update does not work as a drop-in replacement for 0.3.0. We found this out the hard way.

The release notes specify breaking changes. This should have been a 1.0.0 release.

[Major.Minor.Patch](https://semver.org/)

**Comment by vsalahkar** [comment]
Made the update described in the `README.md` → `import { GChart } from 'vue-google-charts/legacy'`

<img width="1099" alt="Screenshot 2022-05-17 at 12 01 52" src="https://user-images.githubusercontent.com/8925597/168786248-be6b37fe-6787-4d2f-8c4a-cc5265117d2f.png">

And it breaks 🥲

Any input on this?

Thanks in advance!

**Comment by thabarbados** [comment]
Sorry guys. We have re-released the version as [1.0.0.](https://github.com/devstark-com/vue-google-charts/releases/tag/v1.0.0)

**Comment by vsalahkar** [comment]
Does it work for Vue 2 projects now @thabarbados?

**Comment by thabarbados** [comment]
@vsalahkar yes, sure. You need to import `import { GChart } from "vue-google-charts/legacy"`. Info about this is in the [docs](https://github.com/devstark-com/vue-google-charts#default-import).
You can check how it works [here](https://codesandbox.io/s/quizzical-moon-xbtx1b)

**Comment by jobithmb** [comment]
@vsalahkar Were you able to figure out a solution for this issue ?

**Comment by Veronika-dev** [comment]
@jobithmb Hi, I fixed it with it
`import { GChart } from 'vue-google-charts/legacy/index.cjs'`

Hope it helps

**Comment by jobithmb** [comment]
> @jobithmb Hi, I fixed it with it `import { GChart } from 'vue-google-charts/legacy/index.cjs'`
> 
> Hope it helps

Thankyou @Veronika-dev It worked for me too. But I would like to know little more about the fix.
