### ISSUE TITLE
loading libraries require internet connection

### ISSUE THREAD

**Issue by pascuapablo** [devstark-com/vue-google-charts#18]
Hi! rendering the charts requires to have an internet connection to download assets from www.gstatic.com.

Possible solutions:
1) add google libraries to /lib folder and load them from there
2) Gchart component could accept an URL param, from where to load google chart libraries.

**Comment by ErikBjare** [comment]
Yeah this was a dealbreaker for me. Was going to use it in [aw-webui](https://github.com/ActivityWatch/aw-webui) but looks like I can't.

**Comment by nobilix** [comment]
Unfortunately, there's limitation by Google:

From https://developers.google.com/chart/interactive/faq :

**Can I use charts offline?**
> Your users' computers must have access to https://www.gstatic.com/charts/loader.js in order to use the interactive features of Google Charts. This is because the visualization libraries that your page requires are loaded dynamically before you use them. The code for loading the appropriate library is part of the included script, and is called when you invoke the google.charts.load() method. Our terms of service **do not allow** you to download the google.charts.load or google.visualization code to use offline.

**Comment by ErikBjare** [comment]
Woah, that's fucking bullshit. Oh well, guess I'll have to go another route. Thanks for the notice @nobilix
