### ISSUE TITLE
redraw graph when data is changed

### ISSUE THREAD

**Issue by yuens1002** [devstark-com/vue-google-charts#20]
i was looking for a way to redraw a chart when data is changed by a $store.commit.  i didn't find anything real obvious in the documentation. but i did manage to come up with a way to do it. Not saying it's the correct way to do it, but it seems to do the trick.  here's what i did...

on the component, data/options both are from vuex store, then on ready event, the method onChartReady is called.

```
<GChart
   type="LineChart"
   :data="chartData"
   :options="chartOptions"
   @ready="onChartReady"
>
</GChart>
```

then in the script's method properties, the store commit ('storeChartInstance') is called which stores the instance of the chart with chart and google as properties of an object.

```
methods: {
  //store instance to call upon when the data is changed
  onChartReady (chart, google) {
    this.$store.commit('storeChartInstance', {chart, google})
  }
}
```

inside vuex store, the mutation ('storeChartInstance') is committed and stores the values in the state like so.

```
storeChartInstance (state, payload) {
  state.chartInstance = payload
}
```

when an user event such as selecting a different set of data from a drop down menu happens, the event triggers a store commit for example  `this.$store.commit('setNewData', val)` to change the data and redraws the chart.

in the store, the mutation ('setNewData') is called, the new data is set and redraws the chart like so assuming the new data is a 2D array and chart has been instantiated with options saved in the store as chartOptions.

```
setNewData (state, payload) {
  state.chartData = payload
  let data = new state.chartInstance.google.visualization.arrayToDataTable(state.chartData)
  state.chartInstance.chart.draw(data, state.chartOptions)
}
```

hope this illustrates the steps clearly and it helps others looking for a similar solution. if anyone has a better way to solve this issue, pls share it.

**Comment by edgarvaldez99** [comment]
any solution for this?

**Comment by alexxlagutin** [comment]
Hi, @yuens1002! Charts will always redraw when you change data. It doesn`t matter where you store it (directly in component or in Vuex). Your solution looks bit overloaded. Here is the Sandbox with shorter one https://codesandbox.io/s/my172nvy79?module=%2Fsrc%2FApp.vue. Please, let us know if it works for you!

**Comment by yuens1002** [comment]
Awesome thanks. I figured out what was going on. Use Vue.set or any of the
array methods that vue watches for changes will work. Sunny
