### ISSUE TITLE
Is It possible to add prefix to GeoCharts tooltip value?

### ISSUE THREAD

**Issue by boka18** [devstark-com/vue-google-charts#21]
Hello! I've used your **awesome** wrapper to create GeoChart. Everything is smooth and working as expected. Really good job!

I only have one question:
Is it possible to format or add prefix to the value in the tooltip? I'm using GeoChart, and I couldn't find a way to do that. Here is a picture:
![vue-google](https://user-images.githubusercontent.com/16739194/45177343-f38c1700-b212-11e8-98f1-0540a904365b.PNG)

What I'm trying to do is to make the value look like this: `$109,67` instead of this `109.67`. Is that possible?

Your help is highly appreciated!

P.S here is how I'm using it:

```
<GChart
    type="GeoChart"
    :data="chartData"
    :options="chartOptions"
/>

chartData: [
    ['State',   'sales'],
    ['TX', 109,67]          <-- this is for reference use only. Originally, I'm dynamically pushing the data in the array
],
chartOptions: {
    region: 'US',
    resolution: 'provinces',
},
```

**Comment by boka18** [comment]
I've found the solution. Actually, it's pretty straightforward. For anyone that is having the same trouble as I was:
```
chartData: [
    ['State',   'sales'],
    ['TX', {v: 109,67, f:'$' + 109,67}]
],
```

**Comment by atmonello** [comment]
Hi @boka18, I got this to work for my chart, but this doesn't seem to be the best solution, specially if we receive the data from an API and/or don't simply enter it from an object or array in our code. 

Have you found any other solution for a more "global" formatter, *eg* adding suffixes or swapping the comma for dots in other locales?

**Comment by fbwang** [comment]
Hi @boka18 ,
May I know how do you add the google API key for GeoChart?

**Comment by Mars073** [comment]
> 
> 
> Hi @boka18 ,
> May I know how do you add the google API key for GeoChart?

if someone is still looking for the answer:
```jsx
<GChart
  :settings="{ packages: ['geochart'], mapsApiKey: 'YOUR_API_KEY' }"
  type="GeoChart"
  :data="chartData"
  :options="chartOptions"
  />
```

bonus link: https://console.cloud.google.com/google/maps-apis/credentials
