### ISSUE TITLE
Responsive features do not seem to be working

### ISSUE THREAD

**Issue by LordOfCorners** [devstark-com/vue-google-charts#23]
The documentation says that the charts should be responsive by default. I've tried adding a resizeDebounce value and it doesn't help. 

This example doesn't seem to be responsive either.
(https://codesandbox.io/embed/z699l6oq4p?module=%2Fsrc%2FApp.vue)

Are my expectations wrong or is it broken?

**Comment by nobilix** [comment]
You just need to use the latest version.
This one uses previous ver:
![image](https://user-images.githubusercontent.com/1443874/45587944-a6e0c400-b915-11e8-9421-7017c945db0c.png)

We will update examples soon, now closing this issue.
