### ISSUE TITLE
i couldn't use the component directly on browser.

### ISSUE THREAD

**Issue by lapcchan** [devstark-com/vue-google-charts#24]
got this error:

[Vue warn]: Unknown custom element: <gchart> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

when using directly on browser with
<script src="vue-google-charts.browser.js"></script>

**Comment by alexxlagutin** [comment]
HI! @lapcchan Here is working usage example https://codesandbox.io/embed/v3qorzrxm7. The problem might be was in order of including files. You have to include the plugin first and then Vue.js. 

@graham-sportsmgmt plugin is hosted on unpkg.com https://unpkg.com/vue-google-charts@latest/dist/vue-google-charts.browser.js and you also can use shorter link like this: https://unpkg.com/vue-google-charts@latest

**Comment by graham-sportsmgmt** [comment]
Pull request created:

https://github.com/devstark-com/vue-google-charts/pull/30

**Comment by niyazpk** [comment]
For anyone else not able to make this work, here is sample code that works for me standalone in the browser (Probably some of these should go to the documentation too):

**HTML:**

    <GChart id="chart" type="ColumnChart" v-bind:data="chartData" v-bind:options="chartOptions"></GChart>
    
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-google-charts@0.3.2/dist/vue-google-charts.browser.js"></script>

**JS:**

    Vue.component("gchart", VueGoogleCharts.GChart);

    let chartData = {
        chartData: [
            ['Year', 'Sales', 'Expenses', 'Profit'],
            ['2014', 1000, 400, 200],
            ['2015', 1170, 460, 250],
            ['2016', 660, 1120, 300],
            ['2017', 1030, 540, 350]
        ],
        chartOptions: {
            chart: {
                title: 'Company Performance',
                subtitle: 'Sales, Expenses, and Profit: 2014-2017',
            }
        }
    }

    let chartVue = new Vue({
        el: '#chart',
        data: chartData
    });

**Comment by SumanBandopadhyay** [comment]
I still face the problem against the chartOption.

I used the above link but it didn't help.
https://codesandbox.io/embed/v3qorzrxm7

The code given here is fine but still, the display present does not show the Options.
