### ISSUE TITLE
Add an example in which we reload the data?

### ISSUE THREAD

**Issue by benoitscherrer** [devstark-com/vue-google-charts#28]
Hi,

I would like to reload the data, ie re-call `onChartReady(chart, google)` when some properties change. 

That would be useful to add interactions between charts for example (we select a date on a chart => other charts update for this date). 

I am able to bind my prop and use a watch to explicitly know when the prop change 
```
watch: {
    date: function (newVal, oldVal) {
      console.log('Prop changed: ', newVal, ' | was: ', oldVal)
    }
},
```
but how would we refresh the component with vue-google-charts? (the Vue machinery doesn't update the component since it doesn t know that the prop was used to load a specific data in onChartReady)

An example could be useful to many.

Many thanks!
B

**Comment by alexxlagutin** [comment]
Hi! @benoitscherrer. `onChartReady` is only the example of method which you can call on when chart is ready. Chart data is reactive and every time you change it - chart will be re-rendered. Here is example  of changing data https://codesandbox.io/s/my172nvy79?module=%2Fsrc%2FApp.vue

**Comment by JamesCoyle** [comment]
You can even add animations to the change by adding the following to the options of the chart: 
```
animation: {
    duration: 1000,
    easing: "out"
}
```
[Animations documentation on google developers](https://google-developers.appspot.com/chart/interactive/docs/animation)
### [Demo](https://codesandbox.io/s/5244xlnk1l)

**Comment by benoitscherrer** [comment]
Thanks so much @alexxlagutin  and @JamesCoyle , that's very useful!
