### ISSUE TITLE
Is "Timeline" chart supported?

### ISSUE THREAD

**Issue by k6pib6r6** [devstark-com/vue-google-charts#33]
When I try to create a timeline chart with type="TimelineChart" I receive the following error message:

vue-google-charts.common.js?877b:1 Uncaught (in promise) TypeError: google.visualization[type] is not a constructor
    at createChart (vue-google-charts.common.js?877b:1)
    at VueComponent.createChartObject (vue-google-charts.common.js?877b:1)
    at eval (vue-google-charts.common.js?877b:1)

I have tried with different variants of type but none of them worked.
May I ask is it supported? 

Thanks in advance.

**Comment by alexxlagutin** [comment]
Hi @k6pib6r6  You have to specify loader you need in settings. (https://github.com/devstark-com/vue-google-charts#load-additional-packages) 
Did you do this correctly?

**Comment by k6pib6r6** [comment]
Thanks alexxlagutin, I was missing that! Thank you for the answer and excuse me for opening an issue for this.

**Comment by andrescastillodf** [comment]
@alexxlagutin  @k6pib6r6 Can you provide an example for a TimeLine chart?

**Comment by valzitos** [comment]
> @alexxlagutin @k6pib6r6 Can you provide an example for a TimeLine chart?
> 
> ```
> `<template>
>   <LayoutManager :name="$system_config.viewSettings.Home.layout">
>     <div>
>       <h1>Employees History</h1>
>       <GChart
>         :settings="{ packages: ['timeline'] }"
>         type="TimeLineChart"
>         :data="data"
>         :options="chartOptions"
>       />
>     </div>
>   </LayoutManager>
> </template>
> 
> <script>
> import { GChart } from "vue-google-charts";
> 
> export default {
>   name: "Home",
>   data() {
>     return {
>       chartOptions: {
>         chart: {
>           title: "Employees History",
>           subtitle: "Time spend at company"
>         }
>       },
>       data: []
>     };
>   },
>   components: {
>     GChart
>   },
>   mounted() {
>     let dataTable = [];
>     dataTable.push(["Employee", "From Date", "To Date"]);
>     dataTable.push(["Washington", "2019-01-01", "2019-10-01"]);
>     dataTable.push(["Adams", "2019-02-01", "2019-5-01"]);
>     dataTable.push(["Jefferson", "2018-02-01", "2019-5-01"]);
>     this.data = dataTable;
>   }
> };
> </script>`
> ```
Just change "TimeLineChart" to "Timeline" according to Google Charts API

**Comment by ThalusA** [comment]
Why does it tells me "Invalid data table format: column #1 must be of type 'date,number,datetime'. With that template ?

**Comment by manuelarte** [comment]
I also get that error about type 'date,number,datetime'. With that template

**Comment by CHOMNANP** [comment]
I'm also not sure how to get timeline working.
