### ISSUE TITLE
Tooltip Example

### ISSUE THREAD

**Issue by mixbyme** [devstark-com/vue-google-charts#37]
Can you upload a tooltip example?

![image](https://user-images.githubusercontent.com/3938097/51299021-3b953300-1a6a-11e9-9a73-14b6156b914b.png)

It does not work.

**Comment by Zexsus** [comment]
You should create `new DataTable()` object from google visualization api, it's working for me
You can get api from @ready event. Look at example below

```javascript
onChartReady(chart, api) {
      const dataTable = new api.visualization.DataTable();
      dataTable.addColumn('string', 'Name');
      dataTable.addColumn('number', 'Sales');
      dataTable.addColumn({
        type: 'string',
        role: 'tooltip',
      });
      dataTable.addRows([
        ['Name', 1000, 'Tooltip string'],
        ['Name', 1170, 'Tooltip string'],
        ['Name', 660, 'Tooltip string'],
      ]);
      this.chartData = dataTable;
    },
```

**Comment by edum18** [comment]
> You should create `new DataTable()` object from google visualization api, it's working for me
> You can get api from @ready event. Look at example below
> 
> ```js
> onChartReady(chart, api) {
>       const dataTable = new api.visualization.DataTable();
>       dataTable.addColumn('string', 'Name');
>       dataTable.addColumn('number', 'Sales');
>       dataTable.addColumn({
>         type: 'string',
>         role: 'tooltip',
>       });
>       dataTable.addRows([
>         ['Name', 1000, 'Tooltip string'],
>         ['Name', 1170, 'Tooltip string'],
>         ['Name', 660, 'Tooltip string'],
>       ]);
>       this.chartData = dataTable;
>     },
> ```

hey, I tried your example and doesn't seem to work, I'm getting the error `Invalid data table format: must have 3 or 4 data columns.`

**Comment by AtmoEntity** [comment]
But what about when the data updates?

Is there any support in the library for this functionality? If I can't bind my vue data to the chart, there's no point in even using this library.
