### ISSUE TITLE
Gauge charts are not working

### ISSUE THREAD

**Issue by gridknight** [devstark-com/vue-google-charts#59]
Unfortunately, the "Gauge" type is not implemented or missing:
```
 <GChart
      type="Gauge"
      :packages="packages"
      :data="chartData"
      :options="chartOptions"
    />    
```
as well as:
```
 <GChart
      type="gauge"
      :packages="packages"
      :data="chartData"
    />    

```
are not working. If I change the type to BarChart everything works. 

On the console I get:
```
vue-google-charts.common.js?757f:1 Uncaught (in promise) TypeError: google.visualization[type] is not a constructor
    at createChart (vue-google-charts.common.js?757f:1)
    at VueComponent.createChartObject (vue-google-charts.common.js?757f:1)
    at eval (vue-google-charts.common.js?757f:1)
```

Therefore it looks like this type is missing.

**Comment by steveDL** [comment]
I am experiencing this same issue is the going to be implemented?

**Comment by alexxlagutin** [comment]
`<template>
  <div>
    <GChart
      type="Gauge"
      :settings="{ packages: 'gauge' }"
      :data="chartData"
      :options="chartOptions"
    />
  </div>
</template>

<script>
import { GChart } from 'vue-google-charts'
export default {
  name: 'App',
  components: {
    GChart
  },
  data () {
    return {
      chartData: [
        ['Label', 'Value'],
        ['Memory', 80],
        ['CPU', 55],
        ['Network', 68]
      ],
      chartOptions: {
        width: 400,
        height: 120,
        redFrom: 90,
        redTo: 100,
        yellowFrom: 75,
        yellowTo: 90,
        minorTicks: 5
      }
    }
  }
}
</script>
`

**Comment by alexxlagutin** [comment]
@steveDL https://github.com/devstark-com/vue-google-charts/issues/82

**Comment by steveDL** [comment]
@alexxlagutin Than you very much for taking the time to get back to me so swiftly! I am using the exact example you posted. Somehow the mime error is gone not sure why but its working anyway thanks again!!

**Comment by alexxlagutin** [comment]
@steveDL Check my comment in #82
You had misprint in package name
