### ISSUE TITLE
Assign a role/customize HTML tooltip to PieChart/DonutChart

### ISSUE THREAD

**Issue by marklreyes** [devstark-com/vue-google-charts#65]
I'm looking to customize a `PieChart` tooltip by leveraging`toolip: {isHtml: true}` which is set here in the options directive,  `:options="chartDonutOptions"`.

The data looks as such:
`      
chartDonutData: [
['Stage', 'Percent', 'Tooltip'],
['Data 1, null, ''],
['Data 2, null, ''],
['Data 3, null, ''],
['Data 4, null, ''],
['Data 5, null, '']
]
`

Note the empty strings on position 2 after `null`. When I make an API call to update this object, I assign values to both the `null` and empty `string` positions. However, when I update string values into those areas, I cannot get them to display when I interact with each slice of the pie. 

Only position 0 and 1 of the array displays:  
**Data 1**
**15.743 (15.7%)**

I expect position 0, 1 and 2 of each row to display:  
**Data 1**
**15.743 (15.7%)**
**My updated string here!**

In my searches, a lot of comments suggest on assigning a role to the column. I'm curious on how you set that with respect to VueJS/vue-google-charts. Please advise!

UPDATED 2020.01.10: I asked this in kind from SO as well,
https://stackoverflow.com/questions/59675457/assign-a-role-customize-html-tooltip-to-piechart-donutchart-google-charts-vuejs/

**Comment by tuansong** [comment]
Good morning @marklreyes, I am struggling while using DonutChart too. I dont know why my chart is not working.
` <GChart
        type="DonutChart"
        :data="chartData"
        :options="chartOptions"
        style="width: 900px; height: 500px;"
      />`

**Comment by marklreyes** [comment]
@tuansong please open a new issue for this inquiry as it has nothing to do with this custom tooltip inquiry. That said, it looks like you are using TypeScript to fully leverage this VueJS wrapper so I'd add those details when writing up your issue.

**Comment by marklreyes** [comment]
This inquiry was answered in StackOverflow:
https://stackoverflow.com/questions/59675457/assign-a-role-customize-html-tooltip-to-piechart-donutchart-google-charts-vuejs/59682077

Closing this issue.
