### ISSUE TITLE
The resource from “https://www.gstatic.com/charts/48.1/js/jsapi_compiled_guage_module.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

### ISSUE THREAD

**Issue by steveDL** [devstark-com/vue-google-charts#82]
When using additional packages I get the above error. I am trying to use the gauge charts like so...

 `<GChart 
            :settings="{ packages: 'guage' }"
            type="Gauge"
            :data="chartData"
            :options="chartOptions"
   />`

Loading other packages seems to work fine.

**Comment by alexxlagutin** [comment]
@steveDL 
Misprint in package name. Change `guage` to  `gauge`
