### ISSUE TITLE
GeoChart: google.visualization[type] is not a constructor

### ISSUE THREAD

**Issue by zappzerapp** [devstark-com/vue-google-charts#88]
Hi,

unfortunately the **GeoChart** does not work anymore. _(without any code adaption since Feb 2019)_

**Error:**
```
Uncaught (in promise) TypeError: google.visualization[type] is not a constructor
    at createChart (app.js?id=7d9ae3605d9708a117dd:220686)
    at VueComponent.createChartObject (app.js?id=7d9ae3605d9708a117dd:220689)
    at app.js?id=7d9ae3605d9708a117dd:220655
```

**Code:**
```
<script>
    import {GChart} from 'vue-google-charts';

    export default {
        components: {
            GChart,
        },
        data() {
            return {
                chartData: [
                    ['Country', 'Users'],
                    ['China', 123],
                    ['Italy', 456],
                    ['Germany', 789],
                ],
                chartOptions: {
//                    mapsApiKey: ***********,
                }
            }
        },
    }
</script>

<template>
    <div>
        <GChart
                type="GeoChart"
                :data="chartData"
                :options="chartOptions"
        />
    </div>
</template>
```

**Comment by RajaHSingh** [comment]
I ran into the same problem, including the geochart package via the settings prop seemed to resolve my issue. So maybe try
<template>
    <div>
        <GChart
                type="GeoChart"
                :data="chartData"
                :options="chartOptions"
		:settings="{ packages: ['geochart'] }"
        />
    </div>
</template>

I also updated to the latest version. Hopefully this helps.

**Comment by ZajdeR** [comment]
The problem is that GChart component override default settings which is `packages: ['corechart', 'table']`. This should be added if you use custom settings chart. 
Better solution will be if author will merge passed custom settings in component.

**Comment by zappzerapp** [comment]
Obviously forgot to close the issue.

Thank you!

**Comment by rawheel** [comment]
IT JUST SAVED MY LIFE HAD BEEN FINDING THE SOLUTION FOR DAYS!!!!
