### ISSUE TITLE
how to :chart intervals

### ISSUE THREAD

**Issue by ramstein74** [devstark-com/vue-google-charts#9]
Hello how can i use your package to draw intervals?
i see the usage of datatables from google to add columns and rows like this
var data = new google.visualization.DataTable();
        data.addColumn('number', 'x');
        data.addColumn('number', 'values');
        data.addColumn({id:'i0', type:'number', role:'interval'});
        data.addColumn({id:'i1', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'number', role:'interval'});
        data.addColumn({id:'i2', type:'boolean', role:'certainty'});
  
        data.addRows([
        		[]
            [1, 130, 90, 110, 85, 96, 104, false],
            [2, 120, 95, 130, 90, 113, 124, true],
            [3, 130, 105, 140, 100, 117, 133, true],
            [4, 90, 85, 95, 85, 88, 92, true],
            [5, 70, 74, 63, 67, 69, 70, true],
            [6, 30, 39, 22, 21, 28, 34, true],
            [7, 80, 77, 83, 70, 77, 85, true],
            [8, 100, 90, 110, 85, 95, 102, true]]);
https://developers.google.com/chart/interactive/docs/gallery/intervals

Can you post an example of intervals with this kind of complex data?

regards and great work

**Comment by nobilix** [comment]
Hey @ramstein74!

Easy enough! You need the Google charts lib outside the Gharts component to implement this. Since it loads asynchronously, the best way to use `@ready` event.

```html
    <GChart
      type="LineChart"
      :data="chartData"
      :options="chartOptions"
      @ready="onChartReady"
    />    
```

```javascript
    // ...
    onChartReady (chart, google) {
      const data = new google.visualization.DataTable();
      // do the stuff like data. addColumn, etc.
      this.chartData = data;
    }
```

See the full example here https://codesandbox.io/embed/1059oz586q?module=%2Fsrc%2FApp.vue
